name: party_san
description: Party.San App
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.8
  flutter_launcher_icons: ^0.7.2+1
  http: ^0.12.0+2
  path_provider: ^1.2.0
  optional: ^3.0.2+1
  webview_flutter: ^0.3.10+4
  flutter_local_notifications: ^0.8.0
  url_launcher: ^5.1.1
  dcache: ^0.3.0
  cloud_firestore: ^0.12.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/initial_schedule.json
     - assets/initialFaq.json
     - assets/bands.json
     - assets/wichtig.jpg

  fonts:
    - family: Beer Money
      fonts:
        - asset: assets/beer_money.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path: "assets/app_logo-1024.png"
  android: true
  adaptive_icon_background: "#dc1f00"
  adaptive_icon_foreground: "assets/app_logo-adaptive.png"
